name: Custom deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  fetch-build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4.1.2

      - name: Clone private repository
        uses: actions/checkout@v4.1.2
        with:
          repository: gabrielkeromnes/tales-of-computing-scenes
          token: ${{ secrets.REACH_PRIVATE_REPOSITORY }}
          path: _includes/dialogs

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.175.0
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install Bundle
        run: bundle install

      - name: Jekyll dependencies
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
